version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: estapar-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=estapar
      - POSTGRES_PASSWORD=estaparpwd
      - POSTGRES_DB=parking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}